// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hyiejgsmboclsuratngr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh5aWVqZ3NtYm9jbHN1cmF0bmdyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc2NjU2NzYsImV4cCI6MjA2MzI0MTY3Nn0.8ycP_fZDq7MP3MoB-7x79IeK-67ecSkHFXmMwNjh-m8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);